### ISSUE TITLE
Option to disable unit removal from calc()

### ISSUE THREAD

**Issue by jbfriedrich** [Josee9988/MinifyAllCli#45]
**Is your feature request related to a problem? Please describe.**
When I am using the Minifier to minify my CSS, it removes that unit from the number in my calc() statements. This seems to be a problem in Chrome, where subtractions of numbers without units will cause an "invalid property value" issue. This is the original CSS:

```css
header {
     margin: 0 calc(0px - (50vw - 50%)) 3rem !important;
}
```

which gets minified to this:

```css
header{margin:0 calc(0 - (50vw - 50%)) 3rem!important;}
```

**Describe the solution you'd like**
I would love to have an option where I could specify that I dont want the Minifier to remove units from numbers (a tickbox would suffice).

**Describe alternatives you've considered**
I am not sure at this point if Chrome is right in reporting an "invalid property value" or if it is a bug. I might file a bug against Chrome later today.
