### ISSUE TITLE
superfluous space and unit in CSS file

### ISSUE THREAD

**Issue by bluedasher13** [Josee9988/MinifyAllCli#59]
**in a CSS file**:

 * before minified:
```css
.className {
  width   :   0%   ;
}
```

 * after minified:
```css
.className{width :0%}
```

 * expected:
```css
.className{width:0}
```

The `space` between property name `width` and colon `:` is not necessary.

And the unit of `0%` is not unnecessary, too. It should be just `0`.
